{{- if or (eq .Values.global.secretStore.backend "vault") (not (hasKey .Values.global.secretStore "backend")) }}
{{- $hashicorp_vault_found := false }}
{{- range .Values.clusterGroup.applications }}
  {{- if eq .chart "hashicorp-vault" }}
    {{- $hashicorp_vault_found = true }}
  {{- end }}
{{- end }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  namespace: golang-external-secrets
spec:
  provider:
    vault:
      server: https://vault-vault.{{ .Values.global.hubClusterDomain }}
      path: secret
      # Version of KV backend
      version: v2
{{- if .Values.golangExternalSecrets.caProvider.enabled }}
{{ if or .Values.clusterGroup.isHubCluster $hashicorp_vault_found }}
      caProvider:
        type: {{ .Values.golangExternalSecrets.caProvider.hostCluster.type }}
        name: {{ .Values.golangExternalSecrets.caProvider.hostCluster.name }}
        key: {{ .Values.golangExternalSecrets.caProvider.hostCluster.key }}
        namespace: {{ .Values.golangExternalSecrets.caProvider.hostCluster.namespace }}
{{ else }}
      caProvider:
        type: {{ .Values.golangExternalSecrets.caProvider.clientCluster.type }}
        name: {{ .Values.golangExternalSecrets.caProvider.clientCluster.name }}
        key: {{ .Values.golangExternalSecrets.caProvider.clientCluster.key }}
        namespace: {{ .Values.golangExternalSecrets.caProvider.clientCluster.namespace }}
{{ end }}
{{- end }}
      auth:
        kubernetes:
{{ if or .Values.clusterGroup.isHubCluster $hashicorp_vault_found }}
          mountPath: {{ .Values.golangExternalSecrets.vault.mountPath }}
          role: {{ .Values.golangExternalSecrets.rbac.rolename }}
{{ else }}
          mountPath: {{ $.Values.global.clusterDomain }}
          role: {{ $.Values.global.clusterDomain }}-role
{{ end }}
          secretRef:
            name: golang-external-secrets
            namespace: golang-external-secrets
            key: "token"
{{- end }}
